export const API_ROUTES = {
  CHECK_EMAIL: "/api/auth/check-email",
  REGISTER_SEND_OTP: "/api/auth/register-send-otp",
  REGISTER_VERIFY_OTP: "/api/auth/register-verify-otp",
  LOGIN: "/api/auth/login",
  INVESTMENT_SHORT_DETAILS: "/api/user/investment-assets-details",
  COMPARE_PORTFOLIO: "/api/analysis/compare",
  CAS_UPLOAD: "/api/portfolio/cas-upload",
  MY_FUND_SUMMARY: "/api/portfolio/my-fund-summary",
  ALL_MYFUND_VIEWS: "/api/portfolio/all-myfund-views",
  USER_DETAILS: "/api/user/details",
  USER_DELETE: "/api/user/delete",
  CAS_DATA_DELETE: "/api/portfolio/cas-data-delete",
  TOTAL_ASSETS: "/api/user/total-assets",
  FD_LIST: "/api/fd",
  FD_CREATE: "/api/fd",
  FD_BY_ID: "/api/fd", // append /:id in service
  DASHBOARD_PRODUCT: "/api/user/get-dashboard-product",
  OTHER_INVESTMENT_ASSETS: "/api/user/other-investment-assets",
  GOLD_CREATE: "/api/gold",
  GOLD_LIST: "/api/gold",
  GOLD_DELETE: "/api/gold",
  RD_CREATE: "/api/rd",
  RD_LIST: "/api/rd",
  RD_DELETE: "/api/rd",
  OTHER_CREATE: "/api/other",
  OTHER_LIST: "/api/other",
  OTHER_DELETE: "/api/other",
  INSURANCE_CREATE: "/api/insurance",
  INSURANCE_LIST: "/api/insurance",
  INSURANCE_DELETE: "/api/insurance",
  FORGOT_PASSWORD_SEND_OTP: "/api/auth/forgot-password-send-otp",
  FORGOT_PASSWORD_RESET: "/api/auth/forgot-password-reset",
  NEWS_FEED: "/api/news/feed",
  NEWS_RELATED: "/api/news/related",
}
